using System;

namespace ProjectEuler
{
    class Program
    {
        static void Main(string[] args)
        {
            //Bu projede project euler sitesinde ki soruların çözümleri olucak.
            //problem1();
            //problem2();
            problem3();

            Console.Read();
        }

        public static void problem1()
        {
            /* 
             If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
             Find the sum of all the multiples of 3 or 5 below 1000.*/
            int limit = 1000;
            int sum = 0;

            for (int i = 0; i<limit; i++)
            {
                if ((i%3==0)||(i%5==0))
                {
                    sum += i;
                }
            }

            Console.WriteLine(String.Format("Cevap = {0}", sum));
        }

        public static void problem2()
        {
            /*
             Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
             1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
             By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

            int first = 1;
            int second = 2;
            int third;
            long sum = 2;

            while (true)
            {
                third = first + second;
                if (third >= 4000000)
                {
                    break;
                }

                Console.WriteLine(third);

                if (third%2==0)
                {
                    sum += third;
                }
                first = second;
                second = third;
            }

            Console.WriteLine(String.Format("Cevap = {0}", sum));
        }

        public static void problem3()
        {
            /*
             The prime factors of 13195 are 5, 7, 13 and 29.
             What is the largest prime factor of the number 600851475143 ?*/

            long starterNumber = 600851475143;
            long max = 0;

            for (long i = 2; i<starterNumber; i++)
            {
                
                if (HelperMethods.isPrime(i))
                {
                    if (starterNumber%i == 0)
                    {
                        Console.WriteLine(i);
                        max = i;
                        starterNumber /= i;
                        
                    }
                }

                Console.WriteLine(i);
                if (starterNumber == 1)
                {
                    break;
                }
            }

            Console.WriteLine(String.Format("Cevap = {0}", max));

        }

        
    }

    static class HelperMethods
    {
        public static bool isPrime(long x)
        {
            bool isPrime = true; // Gelen x sayısını başta asal olarak ele alacağız.

            if (x > 1)
            {
                for (long i = 2; i<x; i++)
                {
                    if (x%i==0)
                    {
                        isPrime = false;
                        break;
                    }
                }
            }
            else
            {
                isPrime = false;
            }

            return isPrime;
        }
    }
}
